### ISSUE TITLE
less redundancy in *seed.yml files

### ISSUE THREAD

**Issue by marvinmarnold** [marvinmarnold/textit_chat#3]
If you look in locales/en.yml, it looks like the convention is to namespace locales like:
@mikevallano , good job on the refactor.

```
en:
    consultation:
        preview: ABC
        question: DEF
```

the seed yml files in lib/tasks should be change accordingly
